# Jekyll configuration
title: HubeiLaoCast
description: Podcasts by HubeiLaoCast
baseurl: ""
url: "https://hubeilaocast.github.io"

# Prevent Jekyll from processing README.md as a standalone page
include: ["README.md"]

# Build settings
markdown: kramdown

collections:
  cptsd_healing:
    output: true       # This tells Jekyll to create a separate page for each chapter
    sort_by: order     # This tells Jekyll to sort the chapters by the 'order' key

kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..4

# Exclude from processing
exclude:
  - .git/
  - .github/
  - vendor/

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

# Enable relative links
relative_links:
  enabled: true
  collections: true

# Permalink structure
permalink: pretty

# Default front matter
defaults:
  - scope:
      path: ""                # Apply to all files...
      type: "cptsd_healing"   # ...but only in this collection
    values:
      layout: "chapter"       # Set their default layout to "chapter"