# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

title: HubeiLaoCast
description: Podcasts by HubeiLaoCast
url: "https://hubeilaocast.github.io"
baseurl: ""

# -----------------------------------------------------------------------------
# Build Settings
# -----------------------------------------------------------------------------

markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..4 # Sets the on-page {:toc} to use h2, h3, and h4

plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

relative_links:
  enabled: true
  collections: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  cptsd_healing_chapters:
    output: true
    # REMOVED: sort_by: order
    # This line conflicts with the manual 'chapter_order' and 'part_order'
    # logic we built for your Next/Previous navigation.

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------
# This section fixes your layout bug.
# Rules are applied top-to-bottom. Specific rules should come last.

defaults:
  # 1. First, set a 'default' layout for ALL files in your site.
  # This fixes the bug with '/CPTSD_Self-help/'.
  - scope:
      path: "" # Apply to all files
    values:
      layout: "default"
      
  # 2. Second, override the layout ONLY for your book.
  # This is more specific and will win for this collection.
  - scope:
      path: ""
      type: "cptsd_healing_chapters" # Only for this collection
    values:
      layout: "chapter"

# -----------------------------------------------------------------------------
# Exclude
# -----------------------------------------------------------------------------
# Files and folders to exclude from the build.

exclude:
  - .git/
  - .github/
  - .jekyll-cache/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules
  # REMOVED: include: ["README.md"] (This is included by default)